# Generated by Django 5.0.6 on 2024-06-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('rpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
