# Generated by Django 5.0.6 on 2024-06-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='rpassword',
            new_name='phno',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='rpassword',
            new_name='phno',
        ),
    ]
