# Generated by Django 5.0.6 on 2024-06-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_rpassword_register_phno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
